/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercise;

import Exercise.commands.CommandFactory;
import Exercise.commands.ICommand;
import Exercise.console.Console;
import Exercise.console.IConsole;
import Exercise.data.Student;
import Exercise.lists.SinglyLinkedList;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {

        SinglyLinkedList<Student> sll = new SinglyLinkedList<>();
        Student s1 = new Student("0", "", 0, 0);
        sll.set(0, s1);
        Student s2 = new Student("1", "", 0, 0);
        sll.add(s2);
        System.out.println(sll.toString());
//        Student s3 = new Student("2", "", 0, 0);
//        sll.add(s3);


//        System.out.println(sll.get(0).toString());
//        System.out.println(sll.get(1).toString());
//        System.out.println(sll.get(2).toString());
//        sll.remove(2);
//        System.out.println(sll.get(2));
        System.out.println("aa");

//        IConsole cnsl = new Console();
//        LinkedList<ICommand> cmds = new CommandFactory(cnsl).returnCommands();
//
//        while (true) {
//            cnsl.write(createMenu(cmds));
//            int n = cnsl.readInteger("Please enter a number for an option:");
//            if (n >= 0 && n < cmds.size()) {
//                cmds.get(n).execute();
//            } else {
//                cnsl.write(String.format("%s option not found", n));
//            }
//        }
    }

    /**
     * Creates Menu with options
     *
     * @param cmds List of executeable Commands
     * @return inteface string
     */
    private static String createMenu(LinkedList<ICommand> cmds) {

        StringBuilder sb = new StringBuilder();
        sb.append("Console-Application: Exercise-1                          Florian Symmank 578767\n");
        sb.append("\n");

        for (int i = 1; i < cmds.size(); i++) {
            sb.append(String.format("%s. %s \n", i, cmds.get(i).toString()));
        }

        sb.append("0. " + cmds.get(0).toString() + "\n");
        return sb.toString();
    }
}